

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5 

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api_gateway:
    build:
      context: ./api_gateway
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api_gateway:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      KAFKA_BROKER: kafka:9092
    depends_on:
       kafka:
          condition: service_healthy
       postgres:
          condition: service_started

  inventory_service:
    build:
      context: ./inventory_service
    ports:
      - "8001:8001"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

  delivery_service:
    build:
      context: ./delivery_service
    ports:
      - "8002:8002"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
       kafka :
        condition: service_healthy

  notification_service:
    build:
      context: ./notification_service
    ports:
      - "8003:8003"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
       kafka :
         condition: service_healthy
volumes:
  postgres_data:
